# Generated by Django 4.2.30 on 2026-08-06 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('calories', 'Calories'), ('protein', 'Protein'), ('carbs', 'Carbohydrates'), ('fat', 'Fat'), ('weight', 'Weight')], db_index=True, max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(help_text='e.g. kcal, g, kg', max_length=20)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start_date', 'goal_type'],
                'indexes': [models.Index(fields=['goal_type', 'active'], name='goals_goal_goal_ty_d0ceb3_idx'), models.Index(fields=['start_date'], name='goals_goal_start_d_d23abc_idx')],
            },
        ),
    ]
